version: "3.7"

services:
  # suricata:
  #   container_name: ips
  #   hostname: ips
  #   image: jasonish/suricata:latest
  #   networks:
  #     - custom_network
  #   cap_add:
  #     - net_admin
  #     - net_raw
  #     - sys_nice
  #   volumes:
      # - ./suricata-config:/etc/suricata
      # - ./suricata-logs:/var/log/suricata
  #   command: ["suricata", "-c", "/etc/suricata/suricata.yaml", "-i", "eth0"]

  nginx:
    container_name: rev-proxy
    # image: nginx:latest
    build:
      context: .
      dockerfile: build-files/Dockerfile_suricata_nginx
    ports:
      - 5555:5555
    networks:
       - custom_network
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - NGINX_REAL_IP_HEADER=proxy_protocol
      - NGINX_REAL_IP_RECURSIVE=on
    volumes:
      - ./suricata-logs:/var/log/suricata
      # - ./suricata-config:/etc/suricata
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - suricata
    restart: always

  emulator-1:
    image: us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
    container_name: android-container
    environment:
      - ADBKEY=$(cat ~/.android/adbkey)
    networks:
       - custom_network
    devices:
      - "/dev/kvm"
    depends_on:
      - nginx

networks:
  custom_network:
    driver: bridge
    

  